id: P010744
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01629
  title: བཀའ་བརྒྱད་བདེ་གཤེགས་འདུས་པའི་སྒྲུབ་ཆེན་གྱི་སྟོང་ཐུན་གདོང་ལྔའི་གད་མོ།
  author: ''
  volumes:
    02c909571da04263a3bfebbaed4f99af:
      image_group_id: I00KG02917
      title: ''
      volume_number: 1
      total_pages: 50
      base_file: v001.txt
