id: I7ABA760F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T06:57:00+00:00'
last_modified: '2022-06-08T17:12:51.191742+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01629
  title: བཀའ་བརྒྱད་བདེ་གཤེགས་འདུས་པའི་སྒྲུབ་ཆེན་གྱི་སྟོང་ཐུན་གདོང་ལྔའི་གད་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EF90:
      image_group_id: I00KG02917
      title: ''
      total_pages: 50
      order: 1
      base_file: EF90.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
